### ISSUE TITLE
Display image files in topicmaps utilizing the dmx-webclient 'objectRenderer' extension mechanism

### ISSUE THREAD

**Issue by silke** [mukil/dmx-images#4]
Hi!

Can I see the images in the webclient? I just see the file topics. Am I doing something wrong or is this not intended / not possible yet?

**Comment by mukil** [comment]
Hi!

> Can I see the images in the webclient?

No, that is not possible yet. We could write a custom object-renderer for image files, but this would then take over (once-instaled) all file-topic renderings. What we need here is a webclient extension mechanism provided by the `dmx-files` webclient plugin so it can delegate object-rendering to other webclient plugins, e.g. depending on the underlying `mimeType` of the file.

I didn't had the time to open a platform issue for that (yet) but we should link it here.

Thanks for reaching out!

**Comment by mukil** [comment]
This was realized within the latest release for platform 5.1.

**Comment by mukil** [comment]
See followup #8 as with platform 5.2 the webclient takes over this task.
